# Application info
info.app:
  name: ${project.name}
  description: ${project.description}
  version: ${project.version}

# Actuator
management:
  endpoints.web.exposure.include: '*'
  endpoint.health.show-details: always

# Various
spring.application.name: ${project.name}
server.port: 8080
spring.boot.admin.client:
  url: http://localhost:82
  username: admin
  password: admin

# Logging levels
logging.level:
  root: INFO
  ${project.group}: INFO

# Disable Groovy templates
spring.groovy.template:
  check-template-location: false
  enabled: false

# Persistence
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/dev?currentSchema=${schemaName}
    username: dev
    password: dev
    initialization-mode: always
  jpa:
    open-in-view: false
  liquibase.change-log: classpath:liquibase-changelog.sql

decorator.datasource.p6spy:
  enable-logging: false
  log-format: '(connection %(connectionId) - %(category)) %(sql)'

# Resilience
resilience4j.retry.instances:
  dummy-checker:
    maxRetryAttempts: 6
    waitDuration: 1s
    enableExponentialBackoff: true
    exponentialBackoffMultiplier: 2
    retryExceptions:
      - java.lang.Exception

# Application
dummy:
  sunrise-sunset.path: 'https://api.sunrise-sunset.org:443'
  location:
    latitude: 52.23
    longitude: 21.01
  checker.cron: '0 0 0 * * *'
  publisher:
    cron: '0 * * * * *'
    topic: 'sunset-task'